apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhbk
spec:
  additionalOptions:
    - name: http-relative-path
      value: /auth
  instances: 2
  db:
    database: keycloak
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: rhbk-db-secret
      key: username
    passwordSecret:
      name: rhbk-db-secret
      key: password
  http:
    tlsSecret: rhbk-tls-secret
  hostname:
    hostname: companysso.apps.cluster-7zh66.dynamic.redhatworkshops.io
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
