apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - commons/01.namespace.yml
  - commons/02.database.yml
  - rhsso/operator/01.operator-group.yml
  - rhsso/operator/02.operator-subscription.yml
  - rhsso/instance/00.psql-db-secret.yml
  - rhsso/instance/01.instance.yml
  - rhsso/instance/02.route.yml

