apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator/01.operator-group.yml
  - operator/02.operator-subscription.yml
  - instance/00.psql-db-secret.yml
  - instance/01.instance.yml
  - instance/02.route.yml

