apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: sso
stringData:
  POSTGRES_DATABASE: keycloak
  POSTGRES_EXTERNAL_ADDRESS: postgres-db.sso.svc.cluster.local
  POSTGRES_EXTERNAL_PORT: "5432"
  POSTGRES_PASSWORD: testpassword
  POSTGRES_SUPERUSER: "true"
  POSTGRES_USERNAME: testuser
type: Opaque
